export const MY_BLOG_URL = 'https://blog.ayane.io'
export const MY_GITHUB_HOMEPAGE_URL = 'https://github.com/miyakoochi'
export const MY_TELEGRAM_INVITE_URL = 'https://t.me/miyakoochi'
export const MY_EMAIL = 'me@ayane.io'
export const RIFF_PROJECT_URL = 'https://github.com/riff-rocks/RIFF'
export const PIKUSERU_PROJECT_URL = 'https://github.com/miyakoochi/pikuseru'
export const COMA_PROJECT_URL = 'https://github.com/miyakoochi/coma'
export const PIKUSHI_PROJECT_URL = 'https://pikushi.ayane.io'
